---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    db:
      - name: molecule_test
    db_users:
      - name: test_user
        password: testpassword
        priv: "molecule_test.*:ALL"
        host: "%"
   
  tasks:
    - name: Check the role
      ansible.builtin.include_role:
        name: mariadb
        tasks_from: main.yml